name: Ottmar at Danasoft
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
<<<<<<< HEAD
<<<<<<< HEAD
gems: [jekyll-coffeescript, jekyll-watch, jekyll-assets, jekyll-admin]
=======
markdown: kramdown
highlighter: rouge

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true

name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://jekyllrb.com

twitter:
  username: jekyllrb

logo: /img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - README.md
- .gitignore
>>>>>>> origin/master
=======
>>>>>>> origin/master
